# Generated by Django 4.2.11 on 2025-07-13 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.IntegerField()),
                ('cargo', models.CharField(max_length=100)),
                ('salario', models.IntegerField()),
            ],
        ),
    ]
