# Generated by Django 4.2.11 on 2025-07-16 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos_adicionais', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicos_adicionais',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
