# Generated by Django 4.2.11 on 2025-07-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospede',
            name='id',
        ),
        migrations.AddField(
            model_name='hospede',
            name='cpf',
            field=models.CharField(default='00000000000', max_length=14, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hospede',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
    ]
