# Generated by Django 4.2.11 on 2025-07-15 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_remove_hospede_id_hospede_cpf_alter_hospede_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospede',
            name='cpf',
            field=models.CharField(max_length=14, primary_key=True, serialize=False),
        ),
    ]
