# Generated by Django 4.2.11 on 2025-07-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(max_length=3, unique=True)),
                ('tipo', models.CharField(max_length=50)),
                ('capacidade', models.IntegerField(max_length=2)),
                ('disponibilidade', models.BooleanField(default=True)),
                ('preco_diaria', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
