# Generated by Django 4.2.11 on 2025-07-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quartos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarto',
            name='capacidade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='quarto',
            name='numero',
            field=models.IntegerField(unique=True),
        ),
    ]
