# Generated by Django 4.2.11 on 2025-07-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quartos', '0002_alter_quarto_capacidade_alter_quarto_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quarto',
            name='id',
        ),
        migrations.AlterField(
            model_name='quarto',
            name='numero',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
