# Generated by Django 4.2.11 on 2025-07-16 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_reserva_servicos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='servicos',
        ),
    ]
